// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package webhook

import (
	"github.com/puppetlabs/pvpool/pkg/apis/pvpool.puppet.com/v1alpha1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckoutValidator) DeepCopyInto(out *CheckoutValidator) {
	*out = *in
	if in.Checkout != nil {
		in, out := &in.Checkout, &out.Checkout
		*out = new(v1alpha1.Checkout)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckoutValidator.
func (in *CheckoutValidator) DeepCopy() *CheckoutValidator {
	if in == nil {
		return nil
	}
	out := new(CheckoutValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CheckoutValidator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolValidator) DeepCopyInto(out *PoolValidator) {
	*out = *in
	if in.Pool != nil {
		in, out := &in.Pool, &out.Pool
		*out = new(v1alpha1.Pool)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolValidator.
func (in *PoolValidator) DeepCopy() *PoolValidator {
	if in == nil {
		return nil
	}
	out := new(PoolValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PoolValidator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
