
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pvpool-puppet-com-v1alpha1-checkout
  failurePolicy: Fail
  name: checkout.validate.webhook.pvpool.puppet.com
  rules:
  - apiGroups:
    - pvpool.puppet.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - checkouts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pvpool-puppet-com-v1alpha1-pool
  failurePolicy: Fail
  name: pool.validate.webhook.pvpool.puppet.com
  rules:
  - apiGroups:
    - pvpool.puppet.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pools
  sideEffects: None
